### PR TITLE
Ed new edits 121420

### PR DESCRIPTION
**Pull request by Erin-Cecele**
Made some small corrections and added Cris Mattison's text. If possible, please leave branch open as I'm sure I'll continue to find little typos. If not, no worries, that's why I started dating the branches.

### CODE REVIEW

**Comment by Erin-Cecele** [comment]
@geealbers I just noticed that there's a conflict with this pull request. It looks like my changes to the homepage are creating the issue but I'm not sure why. They are pretty simple changes. Any ideas?

**Comment by geealbers** [comment]
It's not clear in the interface, but it wasn't a conflict. The Netlify build just failed for some reason. It happens from time to time. I triggered a new build and it it worked. Everything's green and ready to merge in. Should I merge or are you still making changes to this branch?

**Comment by Erin-Cecele** [comment]
You're welcome to merge but I have no doubt I'll come across more typos, changes, etc. Is it more preferable to create a new branch each time I need to make changes or can one branch stay open (after merging) for future edits? 

I've started dating my branches in anticipation of the former being the preference.

**Comment by geealbers** [comment]
I'll just leave this one open and unmerged for now since it's not updating the public site. And you're the only one making changes at the moment so there's no need to keep the primary branch in synch

**Pull request merged**
