### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Erin-Cecele**
based on new website and other tweaks

### CODE REVIEW

**Review by geealbers — APPROVED** [review]

**Comment by geealbers** [comment]
@hbalenda, Erin is updating some of the Markdown files in the monorepo (README, etc.), I assume we don't need to worry about failing CircleCI tests before merging, correct?

**Comment by Erin-Cecele** [comment]
@geealbers for some reason, one of the checks failed. Any ideas why?

**Comment by hbalenda** [comment]
@Erin-Cecele the windows check is expected to fail for the time being because of an issue installing kindle previewer in the test environment, if the others are passing and it's a README change you're good!

**Comment by Erin-Cecele** [comment]
Great thank you @hbalenda. I'll be merging changes to the `README.md` and `CONTRIBUTING.md` to reflect the new website.

**Pull request merged**
